# Generated by Django 3.2.23 on 2024-03-06 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_articles', models.ManyToManyField(related_name='userprofile_saved_articles', to='news.Article')),
                ('selected_categories', models.ManyToManyField(related_name='userprofile_selected_categories', to='news.Category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile_user', to='authentication.user')),
            ],
        ),
    ]
